S := <ws> Resource <ws>
Resource := ResourceType <ws> Name <ws> (ShorthandInit | Block)?

ResourceType := "VPC" | "Subnet" | "EC2"

ShorthandInit := <ws> <'='> <ws> Expr

Block := <'{'> <ws> (Resource | Attribute | <ws>)* <ws> <'}'>

Attribute := Name <ws> (ShorthandInit | Block)

Name := #'[a-zA-Z][a-zA-Z0-9_\-]*'

<Expr> := String | Array | PlainString

String := <'"'> #'([^"\\]|\\.)*' <'"'> |
          <"'"> #"([^'\\]|\\.)*" <"'">

PlainString := #'[^\s\'"{}\[\]]+'

Array := <'['> <ws> (ArrayExpr (<ws> <','> <ws> ArrayExpr)* )? <ws> <']'>
<ArrayExpr> := String | Array | Name

ws := #'\s*'
